package com.c2h6s.etshtinker.init;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.registries.RegistryObject;
import com.c2h6s.etshtinker.Entities.*;
import slimeknights.mantle.registration.deferred.EntityTypeDeferredRegister;

import static com.c2h6s.etshtinker.etshtinker.MOD_ID;
import static com.c2h6s.etshtinker.util.SlashColor.getSlash;

public class etshtinkerEntity {


    public static final EntityTypeDeferredRegister ENTITIES = new EntityTypeDeferredRegister(MOD_ID);
    public static final RegistryObject<EntityType<lightningarrow>> lightningarrow = ENTITIES.register("lightningarrow",()-> EntityType.Builder.<lightningarrow>of(lightningarrow::new, MobCategory.MISC).sized(0.3F, 0.3F).clientTrackingRange(4).updateInterval(20));
    public static final RegistryObject<EntityType<novasickleEntity>> novascikle = ENTITIES.register("novascikle", () -> EntityType.Builder.<novasickleEntity>of(novasickleEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new novasickleEntity(etshtinkerEntity.novascikle.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<exoSlashEntity>> exoslash = ENTITIES.register("exoslash", () -> EntityType.Builder.<exoSlashEntity>of(exoSlashEntity::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(1).setCustomClientFactory((spawnEntity, world) -> new exoSlashEntity(etshtinkerEntity.exoslash.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<shadowaxeEntity>> shadowaxeentity = ENTITIES.register("shadowaxeentity", () -> EntityType.Builder.<shadowaxeEntity>of(shadowaxeEntity::new, MobCategory.MISC).sized(0.3F, 0.3F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new shadowaxeEntity(etshtinkerEntity.shadowaxeentity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<plasmawaveslashentity>> plasmawaveslashEntity = ENTITIES.register("plasmawaveslashentity", () -> EntityType.Builder.of(plasmawaveslashentity::new, MobCategory.MISC).sized(8F, 1F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new plasmawaveslashentity(etshtinkerEntity.plasmawaveslashEntity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<PlasmaArrowEntity>> plasmarrowEntity = ENTITIES.register("plasmarrowentity",()-> EntityType.Builder.<PlasmaArrowEntity>of(PlasmaArrowEntity::new, MobCategory.MISC).sized(0.25F, 0.25F).clientTrackingRange(4).updateInterval(20));
    public static final RegistryObject<EntityType<plasmaexplosionentity>> plasmaexplosionentity = ENTITIES.register("plasmaexplosionentity", () -> EntityType.Builder.of(plasmaexplosionentity::new, MobCategory.MISC).sized(0.75F, 0.75F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new plasmaexplosionentity(etshtinkerEntity.plasmaexplosionentity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<slashentity>> slashentity = ENTITIES.register("slashentity", () -> EntityType.Builder.of(slashentity::new, MobCategory.MISC).sized(0.01F, 0.01F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new slashentity(etshtinkerEntity.slashentity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<phantomswordentity>> phantomswordentity = ENTITIES.register("phantomswordentity", () -> EntityType.Builder.of(phantomswordentity::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new phantomswordentity(etshtinkerEntity.phantomswordentity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<annihilateexplosionentity>> annihilateexplosionentity = ENTITIES.register("annihilateexplosionentity", () -> EntityType.Builder.of(annihilateexplosionentity::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new annihilateexplosionentity(etshtinkerEntity.annihilateexplosionentity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<enchantedswordentity>> enchantedswordentity = ENTITIES.register("enchantedswordentity", () -> EntityType.Builder.<enchantedswordentity>of(enchantedswordentity::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new enchantedswordentity(etshtinkerEntity.enchantedswordentity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<NightSlashEntity>> nights_slash_entity = ENTITIES.register("nights_slash_entity", () -> EntityType.Builder.<NightSlashEntity>of(NightSlashEntity::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new NightSlashEntity(etshtinkerEntity.nights_slash_entity.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<NightSlashEntityB>> nights_slash_entity_b = ENTITIES.register("nights_slash_entity_b", () -> EntityType.Builder.<NightSlashEntityB>of(NightSlashEntityB::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new NightSlashEntityB(etshtinkerEntity.nights_slash_entity_b.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<VibrationAcceptor>> vibration_acceptor = ENTITIES.register("vibration_acceptor", () -> EntityType.Builder.<VibrationAcceptor>of(VibrationAcceptor::new, MobCategory.MISC).sized(0.05F, 0.05F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new VibrationAcceptor(etshtinkerEntity.vibration_acceptor.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<SculkSwordEntity>> sculk_sword = ENTITIES.register("sculk_sword", () -> EntityType.Builder.<SculkSwordEntity>of(SculkSwordEntity::new, MobCategory.MISC).sized(0.05F, 0.05F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new SculkSwordEntity(etshtinkerEntity.sculk_sword.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<CustomSonicBoomEntity>> sonic_boom = ENTITIES.register("sonic_boom", () -> EntityType.Builder.<CustomSonicBoomEntity>of(CustomSonicBoomEntity::new, MobCategory.MISC).sized(0.05F, 0.05F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new CustomSonicBoomEntity(etshtinkerEntity.sonic_boom.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<ShockWaveEntity>> shock_wave = ENTITIES.register("shock_wave", () -> EntityType.Builder.<ShockWaveEntity>of(ShockWaveEntity::new, MobCategory.MISC).sized(0.05F, 0.05F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new ShockWaveEntity(etshtinkerEntity.shock_wave.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<exoLighEntity>> exo_ligh = ENTITIES.register("exo_ligh", () -> EntityType.Builder.<exoLighEntity>of(exoLighEntity::new, MobCategory.MISC).sized(0.05F, 0.05F).setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new exoLighEntity(etshtinkerEntity.exo_ligh.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<exoOrb>> exo_orb = ENTITIES.register("exo_orb", () -> EntityType.Builder.<exoOrb>of(exoOrb::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(1).setCustomClientFactory((spawnEntity, world) -> new exoOrb(etshtinkerEntity.exo_orb.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<PoisonCloud>> poison_cloud = ENTITIES.register("poison_cloud", () -> EntityType.Builder.of(PoisonCloud::new, MobCategory.MISC).sized(0.01F, 0.01F).setTrackingRange(4).setUpdateInterval(1).setCustomClientFactory((spawnEntity, world) -> new PoisonCloud(etshtinkerEntity.poison_cloud.get(), world)).setShouldReceiveVelocityUpdates(true));
    public static final RegistryObject<EntityType<ExoSlashProjectile>> EXO_SLASH = ENTITIES.register("exo_slash", () -> EntityType.Builder.<ExoSlashProjectile>of(ExoSlashProjectile::new, MobCategory.MISC).sized(0.25F, 0.25F).setTrackingRange(4).setUpdateInterval(1).setCustomClientFactory((spawnEntity, world) -> new ExoSlashProjectile(world)).setShouldReceiveVelocityUpdates(true));

    public static final RegistryObject<EntityType<PlasmaSlashEntity>> PLASMA_SLASH = ENTITIES.register("plasma_slash", () ->
            EntityType.Builder.<PlasmaSlashEntity>of(PlasmaSlashEntity::new, MobCategory.MISC).sized(3F, 0.1F)
                    .setTrackingRange(4).setUpdateInterval(10).setCustomClientFactory((spawnEntity, world) -> new PlasmaSlashEntity(world)).setShouldReceiveVelocityUpdates(true));
}
